// THIS FILE IS AUTO GENERATED!
package templates

const ATEST_STYLE string = "atest-style"               // "internal/templates/sample-page.html"
const BODY string = "body"                             // "internal/templates/personal-page.html"
const CLOSE_HTML_TAG string = "close-html-tag"         // "internal/templates/page.html"
const CREATE_ITEM_HTML string = "create-item.html"     // "internal/templates/items/create-item.html"
const DEFAULT_STYLE string = "default-style"           // "internal/templates/page.html"
const HEAD string = "head"                             // "internal/templates/page.html"
const HEAD_EXTRAS string = "head-extras"               // "internal/templates/page.html"
const HOME_HTML string = "home.html"                   // "internal/templates/home.html"
const HOME_PAGE string = "home-page"                   // "internal/templates/home.html"
const HOME_PAGE_BODY string = "home-page-body"         // "internal/templates/home.html"
const ITEMS_CONTAINER string = "items-container"       // "internal/templates/items/item.html"
const ITEM_CONTAINER string = "item-container"         // "internal/templates/items/item.html"
const ITEM_HTML string = "item.html"                   // "internal/templates/items/item.html"
const LOGIN_FORM string = "login-form"                 // "internal/templates/auth/login.html"
const LOGIN_HTML string = "login.html"                 // "internal/templates/auth/login.html"
const LOGIN_PAGE string = "login-page"                 // "internal/templates/auth/login.html"
const OPEN_HTML_TAG string = "open-html-tag"           // "internal/templates/page.html"
const PAGE string = "page"                             // "internal/templates/page.html"
const PAGE_HTML string = "page.html"                   // "internal/templates/page.html"
const PERSONAL_PAGE string = "personal-page"           // "internal/templates/personal-page.html"
const PERSONAL_PAGE_BODY string = "personal-page-body" // "internal/templates/personal-page.html"
const PERSONAL_PAGE_HTML string = "personal-page.html" // "internal/templates/personal-page.html"
const REGISTER_HTML string = "register.html"           // "internal/templates/auth/register.html"
const SAMPLE_PAGE string = "sample-page"               // "internal/templates/sample-page.html"
const SAMPLE_PAGE_BODY string = "sample-page-body"     // "internal/templates/sample-page.html"
const SAMPLE_PAGE_HTML string = "sample-page.html"     // "internal/templates/sample-page.html"
const SCRIPT string = "script"                         // "internal/templates/page.html"
const STATUSBAR string = "statusbar"                   // "internal/templates/page.html"
const STYLE string = "style"                           // "internal/templates/page.html"
const STYLE_DEBUG string = "style-debug"               // "internal/templates/sample-page.html"
