// THIS FILE IS AUTO GENERATED!
// TEMPLATE_<name> is the definition name of that template
// TEMPLATE_<name>_PATH is the file where this definition is

package templates

const (
	TEMPLATE_ATEST_STYLE             string = "atest-style"
	TEMPLATE_ATEST_STYLE_PATH        string = "internal/templates/sample-page.html"
	TEMPLATE_BODY                    string = "body"
	TEMPLATE_BODY_PATH               string = "internal/templates/personal-page.html"
	TEMPLATE_CLOSE_HTML_TAG          string = "close-html-tag"
	TEMPLATE_CLOSE_HTML_TAG_PATH     string = "internal/templates/page.html"
	TEMPLATE_CREATE_ITEM_HTML        string = "create-item.html"
	TEMPLATE_CREATE_ITEM_HTML_PATH   string = "internal/templates/items/create-item.html"
	TEMPLATE_DEFAULT_STYLE           string = "default-style"
	TEMPLATE_DEFAULT_STYLE_PATH      string = "internal/templates/page.html"
	TEMPLATE_HEAD                    string = "head"
	TEMPLATE_HEAD_EXTRAS             string = "head-extras"
	TEMPLATE_HEAD_EXTRAS_PATH        string = "internal/templates/page.html"
	TEMPLATE_HEAD_PATH               string = "internal/templates/page.html"
	TEMPLATE_HOME_HTML               string = "home.html"
	TEMPLATE_HOME_HTML_PATH          string = "internal/templates/home.html"
	TEMPLATE_HOME_PAGE               string = "home-page"
	TEMPLATE_HOME_PAGE_BODY          string = "home-page-body"
	TEMPLATE_HOME_PAGE_BODY_PATH     string = "internal/templates/home.html"
	TEMPLATE_HOME_PAGE_PATH          string = "internal/templates/home.html"
	TEMPLATE_ITEMS_CONTAINER         string = "items-container"
	TEMPLATE_ITEMS_CONTAINER_PATH    string = "internal/templates/items/item.html"
	TEMPLATE_ITEM_CONTAINER          string = "item-container"
	TEMPLATE_ITEM_CONTAINER_PATH     string = "internal/templates/items/item.html"
	TEMPLATE_ITEM_HTML               string = "item.html"
	TEMPLATE_ITEM_HTML_PATH          string = "internal/templates/items/item.html"
	TEMPLATE_LOGIN_FORM              string = "login-form"
	TEMPLATE_LOGIN_FORM_PATH         string = "internal/templates/auth/login.html"
	TEMPLATE_LOGIN_HTML              string = "login.html"
	TEMPLATE_LOGIN_HTML_PATH         string = "internal/templates/auth/login.html"
	TEMPLATE_LOGIN_PAGE              string = "login-page"
	TEMPLATE_LOGIN_PAGE_PATH         string = "internal/templates/auth/login.html"
	TEMPLATE_OPEN_HTML_TAG           string = "open-html-tag"
	TEMPLATE_OPEN_HTML_TAG_PATH      string = "internal/templates/page.html"
	TEMPLATE_PAGE                    string = "page"
	TEMPLATE_PAGE_HTML               string = "page.html"
	TEMPLATE_PAGE_HTML_PATH          string = "internal/templates/page.html"
	TEMPLATE_PAGE_PATH               string = "internal/templates/page.html"
	TEMPLATE_PERSONAL_PAGE           string = "personal-page"
	TEMPLATE_PERSONAL_PAGE_BODY      string = "personal-page-body"
	TEMPLATE_PERSONAL_PAGE_BODY_PATH string = "internal/templates/personal-page.html"
	TEMPLATE_PERSONAL_PAGE_HTML      string = "personal-page.html"
	TEMPLATE_PERSONAL_PAGE_HTML_PATH string = "internal/templates/personal-page.html"
	TEMPLATE_PERSONAL_PAGE_PATH      string = "internal/templates/personal-page.html"
	TEMPLATE_REGISTER_HTML           string = "register.html"
	TEMPLATE_REGISTER_HTML_PATH      string = "internal/templates/auth/register.html"
	TEMPLATE_SAMPLE_PAGE             string = "sample-page"
	TEMPLATE_SAMPLE_PAGE_BODY        string = "sample-page-body"
	TEMPLATE_SAMPLE_PAGE_BODY_PATH   string = "internal/templates/sample-page.html"
	TEMPLATE_SAMPLE_PAGE_HTML        string = "sample-page.html"
	TEMPLATE_SAMPLE_PAGE_HTML_PATH   string = "internal/templates/sample-page.html"
	TEMPLATE_SAMPLE_PAGE_PATH        string = "internal/templates/sample-page.html"
	TEMPLATE_SCRIPT                  string = "script"
	TEMPLATE_SCRIPT_PATH             string = "internal/templates/page.html"
	TEMPLATE_STATUSBAR               string = "statusbar"
	TEMPLATE_STATUSBAR_PATH          string = "internal/templates/page.html"
	TEMPLATE_STYLE                   string = "style"
	TEMPLATE_STYLE_DEBUG             string = "style-debug"
	TEMPLATE_STYLE_DEBUG_PATH        string = "internal/templates/sample-page.html"
	TEMPLATE_STYLE_PATH              string = "internal/templates/page.html"
)
