// THIS FILE IS AUTO GENERATED BY 'template_constants_generator.go'!
// DO NOT EDIT, CHANGES WILL BE LOST!
// TEMPLATE_<name> is the definition name of that template
// TEMPLATE_<name>_PATH is the file where this definition is

package templates

const (
	TEMPLATE_ATEST_STYLE                string = "atest-style"                // internal/routes/sample-page.html
	TEMPLATE_AUTH_PAGE                  string = "auth-page"                  // internal/routes/auth-page.html
	TEMPLATE_AUTH_PAGE_BODY             string = "auth-page-body"             // internal/routes/auth-page.html
	TEMPLATE_BOXES_LIST_CONTENT         string = "boxes-list-content"         // internal/boxes/list-page.html
	TEMPLATE_BOXES_LIST_PAGE            string = "boxes-list-page"            // internal/boxes/list-page.html
	TEMPLATE_BOX_DETAILS                string = "box-details"                // internal/boxes/details-page.html
	TEMPLATE_BOX_DETAILS_PAGE           string = "box-details-page"           // internal/boxes/details-page.html
	TEMPLATE_BOX_LIST_ROW               string = "box-list-row"               // internal/boxes/box-list-row.html
	TEMPLATE_CLOSE_HTML_TAG             string = "close-html-tag"             // internal/templates/page.html
	TEMPLATE_DEFAULT_STYLE              string = "default-style"              // internal/templates/page.html
	TEMPLATE_EMPTY_LIST                 string = "empty-list"                 // internal/boxes/details-page.html
	TEMPLATE_EXTRA_JS                   string = "extra-js"                   // internal/routes/settings-page.html
	TEMPLATE_HEAD                       string = "head"                       // internal/templates/page.html
	TEMPLATE_HEAD_EXTRAS                string = "head-extras"                // internal/templates/page.html
	TEMPLATE_INNERBOXES_LIST            string = "innerboxes-list"            // internal/boxes/details-page.html
	TEMPLATE_ITEMS_CONTAINER            string = "items-container"            // internal/items/item.html
	TEMPLATE_ITEMS_JS                   string = "items-js"                   // internal/items/items-page.html
	TEMPLATE_ITEMS_PAGE                 string = "items-page"                 // internal/items/items-page.html
	TEMPLATE_ITEMS_PAGE_CONTENT         string = "items-page-content"         // internal/items/items-page2.html
	TEMPLATE_ITEM_CONTAINER             string = "item-container"             // internal/items/item.html
	TEMPLATE_ITEM_CONTAINER_2           string = "item-container-2"           // internal/items/item.html
	TEMPLATE_ITEM_CREATE                string = "item-create"                // internal/items/create-item.html
	TEMPLATE_ITEM_CREATE_TEMPLATE       string = "item-create-template"       // internal/items/create-item.html
	TEMPLATE_ITEM_LIST                  string = "item-list"                  // internal/boxes/details-page.html
	TEMPLATE_ITEM_LIST_ROW              string = "item-list-row"              // internal/boxes/details-page.html
	TEMPLATE_ITEM_LIST_UNITS            string = "item-list-units"            // internal/items/item-list-units.html
	TEMPLATE_ITEM_LIST_UNITS_PAGINATION string = "item-list-units-pagination" // internal/items/item-list-units-pagination.html
	TEMPLATE_ITEM_MOVE_TO               string = "item-move-to"               // internal/items/move-item.html
	TEMPLATE_ITEM_PAGE_TEMPLATE         string = "item-page-template"         // internal/items/items-page2.html
	TEMPLATE_LIST                       string = "list"                       // internal/common/list.html
	TEMPLATE_LIST_BUTTONS               string = "list-buttons"               // internal/common/list.html
	TEMPLATE_LIST_TABLE                 string = "list-table"                 // internal/common/list.html
	TEMPLATE_LOGIN_FORM                 string = "login-form"                 // internal/auth/login.html
	TEMPLATE_LOGIN_PAGE                 string = "login-page"                 // internal/auth/login.html
	TEMPLATE_NAVBAR                     string = "navbar"                     // internal/templates/page.html
	TEMPLATE_NOTIFICATION_CONTAINER     string = "notification-container"     // internal/templates/page.html
	TEMPLATE_OOB_NOTIFICATION           string = "oob-notification"           // internal/templates/page.html
	TEMPLATE_OPEN_HTML_TAG              string = "open-html-tag"              // internal/templates/page.html
	TEMPLATE_PAGE                       string = "page"                       // internal/templates/page.html
	TEMPLATE_PAGE_CONTENT               string = "page-content"               // internal/templates/page.html
	TEMPLATE_PERSONAL_PAGE              string = "personal-page"              // internal/routes/personal-page.html
	TEMPLATE_PERSONAL_PAGE_BODY         string = "personal-page-body"         // internal/routes/personal-page.html
	TEMPLATE_REGISTER_FORM              string = "register-form"              // internal/auth/register.html
	TEMPLATE_REGISTER_PAGE              string = "register-page"              // internal/auth/register.html
	TEMPLATE_SAMPLE_PAGE                string = "sample-page"                // internal/routes/sample-page.html
	TEMPLATE_SAMPLE_PAGE_BODY           string = "sample-page-body"           // internal/routes/sample-page.html
	TEMPLATE_SCRIPT                     string = "script"                     // internal/templates/page.html
	TEMPLATE_SEARCH_INPUT               string = "search-input"               // internal/common/search-input.html
	TEMPLATE_SEARCH_ITEM_FORM           string = "search-item-form"           // internal/items/search-item.html
	TEMPLATE_SELECTED_INPUT             string = "selected-input"             // internal/common/list.html
	TEMPLATE_SETTINGS_PAGE              string = "settings-page"              // internal/routes/settings-page.html
	TEMPLATE_SETTINGS_PAGE_CONTENT      string = "settings-page-content"      // internal/routes/settings-page.html
	TEMPLATE_SHELF_CREATE               string = "shelf-create"               // internal/shelves/shelf-create-page.html
	TEMPLATE_SHELF_CREATE_PAGE          string = "shelf-create-page"          // internal/shelves/shelf-create-page.html
	TEMPLATE_SHELF_DETAILS              string = "shelf-details"              // internal/shelves/shelf-details-page.html
	TEMPLATE_SHELF_DETAILS_PAGE         string = "shelf-details-page"         // internal/shelves/shelf-details-page.html
	TEMPLATE_SHELF_LIST                 string = "shelf-list"                 // internal/shelves/shelf-list.html
	TEMPLATE_SHELF_LIST_ROW             string = "shelf-list-row"             // internal/shelves/shelf-list-row.html
	TEMPLATE_SHELF_PAGINATION_UNIT      string = "shelf-pagination-unit"      // internal/shelves/shelf-pagination.html
	TEMPLATE_SHELVES_JS                 string = "shelves-js"                 // internal/shelves/shelves-page.html
	TEMPLATE_SHELVES_PAGE               string = "shelves-page"               // internal/shelves/shelves-page.html
	TEMPLATE_SHELVES_PAGE_CONTENT       string = "shelves-page-content"       // internal/shelves/shelves-page.html
	TEMPLATE_STYLE                      string = "style"                      // internal/templates/page.html
	TEMPLATE_STYLE_DEBUG                string = "style-debug"                // internal/routes/sample-page.html
	TEMPLATE_TEST_PAGE                  string = "test-page"                  // internal/routes/test-page.html
	TEMPLATE_TEST_PAGE_BODY             string = "test-page-body"             // internal/routes/test-page.html
	TEMPLATE_UPDATE_USER                string = "update-user"                // internal/auth/update.html
)
